name: hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - netCDF4
  - pandas
  - matplotlib
  - seaborn  # df plotting
  - pytest  # development
  - pylint  # development
  - flake8  # development
  - autopep8  # development
  - ipykernel  # jupyter notebooks
  # - statannotations  # for df stats
  - pip
  - pip:
    - specparam
    - -e .  # fooof and mne-multi-connectivity and scripts
    # - ptitprince  # remember to cite, raincloudplots
    # - numpy==1.23.4  # otherwise ptitprince does not work
    # - pte-stats  # Richard's stats for cluster permutation tests