name: hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - netCDF4
  - pandas
  - matplotlib
  - seaborn  # df plotting
  - pytest  # development
  - pylint  # development
  - flake8  # development
  - autopep8  # development
  - ipykernel  # jupyter notebooks
  - pip
  - pip:
    - specparam
    - pingouin
    - -e .